//go:build windows
package main

import("fmt";"strconv";"strings";"syscall";"unsafe")

const(lvmFirst=0x1000;lvmSetExtended=0x1036;lvmDeleteAll=0x1009;lvmDeleteColumn=0x100C;lvmInsertColumnW=0x1061;lvmInsertItemW=0x104D;lvmSetItemTextW=0x1074;lvmGetColumnOrderArray=0x103B;lvmSetColumnWidth=0x101E;lvmGetColumnWidth=0x101D;lvscwAutosize int32=-1;lvifText=1;lvcfText=4;lvcfmtLeft=0;lvcfmtRight=1;lvsReport=1;lvsExGridlines=1;lvsExFullRowSelect=0x20;lvsExDoubleBuffer=0x10000;lvsExHeaderDragDrop=0x40;mfString=0;mfChecked=8;tpmRetCmd=0x100;bmGetCheck=0xF0;bmSetCheck=0xF1;bstChecked=1;configIDOK=3101;configIDCancel=3102;configIDDecimals=3103;configIDFont=3104;configIDSOColumn=3105;configIDJoin=3106;configIDFormulaTitle=3107;configIDFormula=3108;configIDSubtotal=3109;configIDSubtotalCheck=3110;configIDNames=3111;configIDMaxColumns=3112;configClass="GestionSOConfig";namesClass="GestionSONames";menuIDClearFilters=39997;menuIDSelectAll=39998;menuIDDeselectAll=39999;filterBaseID=50000;esAutoHScroll=0x80;lvnEndDrag=-109)

type lvColumn struct{Mask uint32;Fmt,Cx int32;Text *uint16;TextMax,SubItem,Image,Order int32}
type lvItem struct{Mask uint32;Item,SubItem int32;State,StateMask uint32;Text *uint16;TextMax,Image int32;Param uintptr}
type nmhdr struct{HwndFrom,IDFrom uintptr;Code int32}
var(viewList uintptr;viewFont uintptr;viewDataset *MemoryDataset;viewMenuIDs=map[uintptr]int{};viewFilters=map[string]uintptr{};configHwnd uintptr;configEdits=map[int]uintptr{};configParent uintptr;namesHwnd uintptr;namesEdits=map[string]uintptr{};namesParent uintptr)

func columnViewCreate(hwnd uintptr)uintptr{viewList=appMake(hwnd,"SysListView32","",WS_CHILD|WS_VISIBLE|WS_BORDER|WS_TABSTOP|lvsReport,0,0,100,100,appIDView);user32.NewProc("SendMessageW").Call(viewList,lvmSetExtended,0,lvsExGridlines|lvsExFullRowSelect|lvsExDoubleBuffer|lvsExHeaderDragDrop);return viewList}
func columnViewLayout(hwnd uintptr,w,h int){if viewList==0{return};user32.NewProc("MoveWindow").Call(viewList,10,84,uintptr(maxInt(300,w-20)),uintptr(maxInt(150,h-94)),1);columnViewLayoutFilters(w)}
func columnViewDestroy(){columnViewDestroyFilters();if viewFont!=0{user32.NewProc("DeleteObject").Call(viewFont);viewFont=0};viewList=0}
func columnViewSetDataset(ds *MemoryDataset){columnViewDestroyFilters();viewDataset=ds;columnViewBuildFilters();columnViewRefresh()}
func columnViewDestroyFilters(){for _,h:=range viewFilters{if h!=0{user32.NewProc("DestroyWindow").Call(h)}};viewFilters=map[string]uintptr{}}
func columnViewBuildFilters(){if viewDataset==nil||appHwnd==0{return};for i,c:=range columnViewVisibleColumns(){h:=appMake(appHwnd,"EDIT","",WS_CHILD|WS_VISIBLE|WS_BORDER|WS_TABSTOP|esAutoHScroll,10,55,maxInt(120,c.Width),24,uintptr(filterBaseID+i));viewFilters[c.ID]=h};columnViewLayoutFilters(currentClientWidth())}
func currentClientWidth()int{if appHwnd==0{return 1000};var r appRect;user32.NewProc("GetClientRect").Call(appHwnd,uintptr(unsafe.Pointer(&r)));return int(r.Right-r.Left)}
func columnViewLayoutFilters(w int){if viewDataset==nil{return};x:=10;for _,c:=range columnViewVisibleColumns(){h:=viewFilters[c.ID];width:=maxInt(120,c.Width);if h!=0{user32.NewProc("MoveWindow").Call(h,uintptr(x),55,uintptr(width),24,1)};x+=width};_ = w}
func columnViewVisibleColumns()[]DatasetColumn{if viewDataset==nil{return nil};out:=[]DatasetColumn{};used:=map[string]bool{};limit:=appSettings.MaxColumns;if limit<1{limit=20};appendColumn:=func(c DatasetColumn){if len(out)>=limit||used[c.ID]||!c.Visible{return};out=append(out,c);used[c.ID]=true};for _,key:=range appSettings.ColumnOrder{for _,c:=range viewDataset.Columns{if datasetColumnKey(c)==key{appendColumn(c);break}}};for _,c:=range viewDataset.Columns{appendColumn(c)};return out}
func columnViewFilteredRecords()[]DatasetRecord{if viewDataset==nil{return nil};out:=[]DatasetRecord{};for _,r:=range viewDataset.Records{ok:=true;for id,h:=range viewFilters{f:=strings.ToLower(strings.TrimSpace(appGetEdit(h)));if f!=""{var c DatasetColumn;found:=false;for _,x:=range viewDataset.Columns{if x.ID==id{c=x;found=true;break}};if !found||!strings.Contains(strings.ToLower(datasetCellText(r,c)),f){ok=false;break}}};if ok{out=append(out,r)}};return out}
func columnViewHandleFilterChange(id uintptr){if id<filterBaseID{return};columnViewRefresh()}
func columnViewDeleteColumns(){if viewList==0{return};for{r,_,_:=user32.NewProc("SendMessageW").Call(viewList,lvmDeleteColumn,0,0);if r==0{break}}}
func columnViewAutoFit(visible []DatasetColumn){if viewList==0{return};for i:=range visible{user32.NewProc("SendMessageW").Call(viewList,lvmSetColumnWidth,uintptr(i),uintptr(uint32(lvscwAutosize)));width,_,_:=user32.NewProc("SendMessageW").Call(viewList,lvmGetColumnWidth,uintptr(i),0);w:=int(width);if w<120{w=120};if w>500{w=500};user32.NewProc("SendMessageW").Call(viewList,lvmSetColumnWidth,uintptr(i),uintptr(w));visible[i].Width=w;for j:=range viewDataset.Columns{if viewDataset.Columns[j].ID==visible[i].ID{viewDataset.Columns[j].Width=w;break}}}}
func columnViewRefresh(){if viewList==0{return};columnViewDeleteColumns();user32.NewProc("SendMessageW").Call(viewList,lvmDeleteAll,0,0);if viewDataset==nil{return};visible:=columnViewVisibleColumns();for i,c:=range visible{p:=appU16(datasetColumnDisplayTitle(c));fmtCol:=lvcfmtLeft;if c.Type==ValueNumber{fmtCol=lvcfmtRight};lc:=lvColumn{Mask:lvcfText,Fmt:int32(fmtCol),Cx:int32(maxInt(120,c.Width)),Text:p,SubItem:int32(i)};user32.NewProc("SendMessageW").Call(viewList,lvmInsertColumnW,uintptr(i),uintptr(unsafe.Pointer(&lc)))};records:=columnViewFilteredRecords();for ri,r:=range records{for ci,c:=range visible{txt:=datasetCellText(r,c);p:=appU16(txt);it:=lvItem{Mask:lvifText,Item:int32(ri),SubItem:int32(ci),Text:p,TextMax:int32(len([]rune(txt))+1)};if ci==0{user32.NewProc("SendMessageW").Call(viewList,lvmInsertItemW,0,uintptr(unsafe.Pointer(&it)))}else{user32.NewProc("SendMessageW").Call(viewList,lvmSetItemTextW,uintptr(ri),uintptr(unsafe.Pointer(&it)))}}};if appSettings.SubtotalEnabled&&appSettings.SubtotalColumn!=""{columnViewAddSubtotal(visible,records)};columnViewAutoFit(visible);columnViewLayoutFilters(currentClientWidth());columnViewApplyFont()}
func datasetCellText(r DatasetRecord,c DatasetColumn)string{if v,ok:=r.Values[c.ID];ok{if v.Type==ValueNumber{n:=v.Number;if datasetColumnIsPercent(c){n*=100;return formatDatasetNumber(n,datasetColumnDecimals(c))+"%"};return formatDatasetNumber(n,datasetColumnDecimals(c))};return cleanCell(v.Raw)};return ""}
func columnViewAddSubtotal(visible []DatasetColumn,records []DatasetRecord){targets:=map[string]bool{};if len(appSettings.SubtotalColumns)>0{for _,t:=range appSettings.SubtotalColumns{targets[strings.ToLower(strings.TrimSpace(t))]=true}}else if appSettings.SubtotalColumn!=""{targets[strings.ToLower(strings.TrimSpace(appSettings.SubtotalColumn))]=true};sums:=map[string]float64{};for _,c:=range visible{if targets[strings.ToLower(strings.TrimSpace(c.Title))]||targets[strings.ToLower(strings.TrimSpace(datasetColumnDisplayTitle(c)))]{for _,r:=range records{if v,ok:=r.Values[c.ID];ok&&v.Type==ValueNumber{sums[c.ID]+=v.Number}}}};idx:=len(records);for ci,c:=range visible{txt:="";if ci==0{txt="SUBTOTAL"};if sum,ok:=sums[c.ID];ok{if datasetColumnIsPercent(c){sum*=100;txt=formatDatasetNumber(sum,datasetColumnDecimals(c))+"%"}else{txt=formatDatasetNumber(sum,datasetColumnDecimals(c))}};p:=appU16(txt);it:=lvItem{Mask:lvifText,Item:int32(idx),SubItem:int32(ci),Text:p,TextMax:int32(len([]rune(txt))+1)};if ci==0{user32.NewProc("SendMessageW").Call(viewList,lvmInsertItemW,0,uintptr(unsafe.Pointer(&it)))}else{user32.NewProc("SendMessageW").Call(viewList,lvmSetItemTextW,uintptr(idx),uintptr(unsafe.Pointer(&it)))}}}
func columnViewApplyFont(){if viewList==0{return};if viewFont!=0{user32.NewProc("DeleteObject").Call(viewFont)};gdi:=syscall.NewLazyDLL("gdi32.dll");height:=int32(-appSettings.FontSize);viewFont,_,_=gdi.NewProc("CreateFontW").Call(uintptr(height),0,0,0,400,0,0,0,1,0,0,0,0,uintptr(unsafe.Pointer(appU16("Segoe UI"))));if viewFont!=0{user32.NewProc("SendMessageW").Call(viewList,WM_SETFONT,viewFont,1)}}
func columnViewShowMenu(hwnd uintptr){if viewDataset==nil{return};m,_,_:=user32.NewProc("CreatePopupMenu").Call();viewMenuIDs=map[uintptr]int{};appendMenu:=user32.NewProc("AppendMenuW");appendMenu.Call(m,uintptr(mfString),menuIDClearFilters,uintptr(unsafe.Pointer(appU16("LIMPIAR FILTROS"))));appendMenu.Call(m,uintptr(mfString),menuIDSelectAll,uintptr(unsafe.Pointer(appU16("MARCAR TODAS"))));appendMenu.Call(m,uintptr(mfString),menuIDDeselectAll,uintptr(unsafe.Pointer(appU16("DESMARCAR TODAS"))));appendMenu.Call(m,uintptr(mfString),0,uintptr(unsafe.Pointer(appU16("--------------------"))));for i,c:=range viewDataset.Columns{id:=uintptr(40000+i);f:=uint32(mfString);if c.Visible{f|=mfChecked};appendMenu.Call(m,uintptr(f),id,uintptr(unsafe.Pointer(appU16(datasetColumnDisplayTitle(c)))));viewMenuIDs[id]=i};var pt struct{X,Y int32};user32.NewProc("GetCursorPos").Call(uintptr(unsafe.Pointer(&pt)));sel,_,_:=user32.NewProc("TrackPopupMenu").Call(m,tpmRetCmd,uintptr(pt.X),uintptr(pt.Y),0,hwnd,0);changed:=false;switch sel{case menuIDClearFilters:for _,h:=range viewFilters{appSetEdit(h,"")};columnViewRefresh();case menuIDSelectAll:limit:=appSettings.MaxColumns;if limit<1{limit=20};for i:=range viewDataset.Columns{viewDataset.Columns[i].Visible=i<limit};changed=true;case menuIDDeselectAll:for i:=range viewDataset.Columns{viewDataset.Columns[i].Visible=false};changed=true;default:if i,ok:=viewMenuIDs[sel];ok{if !viewDataset.Columns[i].Visible&&len(columnViewVisibleColumns())>=appSettings.MaxColumns{break};viewDataset.Columns[i].Visible=!viewDataset.Columns[i].Visible;changed=true}};if changed{_ = saveDatasetSettings(appSettings);columnViewDestroyFilters();columnViewBuildFilters();columnViewRefresh()};user32.NewProc("DestroyMenu").Call(m)}
func columnViewSaveOrder(){if viewList==0||viewDataset==nil{return};visible:=columnViewVisibleColumns();n:=len(visible);if n==0{return};arr:=make([]int32,n);r,_,_:=user32.NewProc("SendMessageW").Call(viewList,lvmGetColumnOrderArray,uintptr(n),uintptr(unsafe.Pointer(&arr[0])));if r==0{return};order:=make([]string,0,n);for _,idx:=range arr{if int(idx)>=0&&int(idx)<len(visible){order=append(order,datasetColumnKey(visible[idx]))}};appSettings.ColumnOrder=order;_ = saveDatasetSettings(appSettings)}
func columnViewHandleNotify(l uintptr)bool{if l==0{return false};n:=(*nmhdr)(unsafe.Pointer(l));if n.Code==lvnEndDrag{columnViewSaveOrder();return true};return false}
func datasetShowConfig(parent uintptr){if configHwnd!=0{return};configParent=parent;cls:=appU16(configClass);wc:=appWndClass{CbSize:uint32(unsafe.Sizeof(appWndClass{})),LpfnWndProc:syscall.NewCallback(configWndProc),HInstance:appHInstance,HCursor:loadArrowCursor(),LpszClassName:cls};user32.NewProc("RegisterClassExW").Call(uintptr(unsafe.Pointer(&wc)));configHwnd,_,_=user32.NewProc("CreateWindowExW").Call(0,uintptr(unsafe.Pointer(cls)),uintptr(unsafe.Pointer(appU16("Configuración de presentación y cálculo"))),WS_OVERLAPPEDWINDOW|WS_VISIBLE,300,150,650,500,parent,0,appHInstance,0);fields:=[]struct{id int;label string;y int}{{configIDDecimals,"Decimales predeterminados",20},{configIDFont,"Tamaño de fuente",55},{configIDSOColumn,"Columna N° donde está el ID de SO",90},{configIDJoin,"Columna Excel para cruzar con CSV",125},{configIDFormulaTitle,"Nombre columna calculada",160},{configIDFormula,"Fórmula (use [COLUMNA])",195},{configIDSubtotal,"Columna(s) para subtotal, separadas por ;",230},{configIDMaxColumns,"Máximo de columnas visibles",265}};for _,f:=range fields{appMake(configHwnd,"STATIC",f.label,WS_CHILD|WS_VISIBLE,20,f.y,300,22,0);configEdits[f.id]=appMake(configHwnd,"EDIT","",WS_CHILD|WS_VISIBLE|WS_BORDER|WS_TABSTOP|esAutoHScroll,325,f.y,280,24,uintptr(f.id))};check:=appMake(configHwnd,"BUTTON","Subtotal habilitado",WS_CHILD|WS_VISIBLE|WS_TABSTOP|0x3,20,300,200,26,configIDSubtotalCheck);if appSettings.SubtotalEnabled{user32.NewProc("SendMessageW").Call(check,bmSetCheck,bstChecked,0)};appSetEdit(configEdits[configIDDecimals],fmt.Sprint(appSettings.Decimals));appSetEdit(configEdits[configIDFont],fmt.Sprint(appSettings.FontSize));appSetEdit(configEdits[configIDSOColumn],fmt.Sprint(appSettings.SOColumn));appSetEdit(configEdits[configIDJoin],appSettings.JoinExcelColumn);appSetEdit(configEdits[configIDFormulaTitle],appSettings.FormulaTitle);appSetEdit(configEdits[configIDFormula],appSettings.Formula);if len(appSettings.SubtotalColumns)>0{appSetEdit(configEdits[configIDSubtotal],strings.Join(appSettings.SubtotalColumns,";"))}else{appSetEdit(configEdits[configIDSubtotal],appSettings.SubtotalColumn)};appSetEdit(configEdits[configIDMaxColumns],fmt.Sprint(appSettings.MaxColumns));appMake(configHwnd,"BUTTON","EDITAR NOMBRES",WS_CHILD|WS_VISIBLE|WS_TABSTOP,280,350,115,30,configIDNames);appMake(configHwnd,"BUTTON","GUARDAR",WS_CHILD|WS_VISIBLE|WS_TABSTOP,400,350,100,30,configIDOK);appMake(configHwnd,"BUTTON","CANCELAR",WS_CHILD|WS_VISIBLE|WS_TABSTOP,510,350,100,30,configIDCancel);appSetEnabled(parent,false)}
func appSetEdit(h uintptr,s string){p:=appU16(s);user32.NewProc("SetWindowTextW").Call(h,uintptr(unsafe.Pointer(p)))}
func appGetEdit(h uintptr)string{n,_,_:=user32.NewProc("GetWindowTextLengthW").Call(h);b:=make([]uint16,n+1);user32.NewProc("GetWindowTextW").Call(h,uintptr(unsafe.Pointer(&b[0])),n+1);return strings.TrimSpace(syscall.UTF16ToString(b))}
func configWndProc(hwnd uintptr,msg uint32,wp,lp uintptr)uintptr{if msg==WM_COMMAND{switch int(wp&0xffff){case configIDNames:datasetShowNames(hwnd);return 0;case configIDOK:d,_:=strconv.Atoi(appGetEdit(configEdits[configIDDecimals]));f,_:=strconv.Atoi(appGetEdit(configEdits[configIDFont]));so,_:=strconv.Atoi(appGetEdit(configEdits[configIDSOColumn]));mc,_:=strconv.Atoi(appGetEdit(configEdits[configIDMaxColumns]));if d<0||d>8{d=2};if f<8||f>32{f=10};if so<1||so>1024{so=5};if mc<1||mc>100{mc=20};appSettings.Decimals=d;appSettings.FontSize=f;appSettings.SOColumn=so;appSettings.MaxColumns=mc;appSettings.JoinExcelColumn=appGetEdit(configEdits[configIDJoin]);appSettings.FormulaTitle=appGetEdit(configEdits[configIDFormulaTitle]);appSettings.Formula=appGetEdit(configEdits[configIDFormula]);rawSubs:=appGetEdit(configEdits[configIDSubtotal]);appSettings.SubtotalColumns=nil;for _,x:=range strings.Split(rawSubs,";"){x=strings.TrimSpace(x);if x!=""{appSettings.SubtotalColumns=append(appSettings.SubtotalColumns,x)}};if len(appSettings.SubtotalColumns)>0{appSettings.SubtotalColumn=appSettings.SubtotalColumns[0]}else{appSettings.SubtotalColumn=""};check:=findChildByID(hwnd,"BUTTON",configIDSubtotalCheck);r,_,_:=user32.NewProc("SendMessageW").Call(check,bmGetCheck,0,0);appSettings.SubtotalEnabled=r==bstChecked;_ = saveDatasetSettings(appSettings);appApplySettings();configClose();return 0;case configIDCancel:configClose();return 0}};if msg==WM_CLOSE{configClose();return 0};return user32Def(hwnd,msg,wp,lp)}
func configClose(){for k:=range configEdits{delete(configEdits,k)};if configHwnd!=0{user32.NewProc("DestroyWindow").Call(configHwnd);configHwnd=0};if configParent!=0{appSetEnabled(configParent,true);configParent=0}}
func datasetShowNames(parent uintptr){if namesHwnd!=0||viewDataset==nil{return};namesParent=parent;cls:=appU16(namesClass);wc:=appWndClass{CbSize:uint32(unsafe.Sizeof(appWndClass{})),LpfnWndProc:syscall.NewCallback(namesWndProc),HInstance:appHInstance,HCursor:loadArrowCursor(),LpszClassName:cls};user32.NewProc("RegisterClassExW").Call(uintptr(unsafe.Pointer(&wc)));namesHwnd,_,_=user32.NewProc("CreateWindowExW").Call(0,uintptr(unsafe.Pointer(cls)),uintptr(unsafe.Pointer(appU16("Editar nombres de columnas"))),WS_OVERLAPPEDWINDOW|WS_VISIBLE,350,120,700,650,parent,0,appHInstance,0);namesEdits=map[string]uintptr{};y:=20;for _,c:=range viewDataset.Columns{appMake(namesHwnd,"STATIC",c.Title,WS_CHILD|WS_VISIBLE,20,y,270,22,0);h:=appMake(namesHwnd,"EDIT",datasetColumnDisplayTitle(c),WS_CHILD|WS_VISIBLE|WS_BORDER|WS_TABSTOP|esAutoHScroll,300,y,330,24,uintptr(45000+y));namesEdits[datasetColumnKey(c)]=h;y+=32;if y>540{break}};appMake(namesHwnd,"STATIC","El nombre cambia solo la presentación; no modifica IDs, datos ni fórmulas.",WS_CHILD|WS_VISIBLE,20,560,620,22,0);appMake(namesHwnd,"BUTTON","GUARDAR",WS_CHILD|WS_VISIBLE|WS_TABSTOP,500,585,110,30,45001);appMake(namesHwnd,"BUTTON","CANCELAR",WS_CHILD|WS_VISIBLE|WS_TABSTOP,615,585,80,30,45002);appSetEnabled(parent,false)}
func namesWndProc(hwnd uintptr,msg uint32,wp,lp uintptr)uintptr{if msg==WM_COMMAND{switch int(wp&0xffff){case 45001:for key,h:=range namesEdits{v:=appGetEdit(h);if appSettings.ColumnTitles==nil{appSettings.ColumnTitles=map[string]string{}};for _,c:=range viewDataset.Columns{if datasetColumnKey(c)==key{if strings.TrimSpace(v)==""||strings.EqualFold(strings.TrimSpace(v),c.Title){delete(appSettings.ColumnTitles,key)}else{appSettings.ColumnTitles[key]=v};break}}};_ = saveDatasetSettings(appSettings);columnViewRefresh();namesClose();return 0;case 45002:namesClose();return 0}};if msg==WM_CLOSE{namesClose();return 0};return user32Def(hwnd,msg,wp,lp)}
func namesClose(){for k:=range namesEdits{delete(namesEdits,k)};if namesHwnd!=0{user32.NewProc("DestroyWindow").Call(namesHwnd);namesHwnd=0};if namesParent!=0{appSetEnabled(namesParent,true);namesParent=0}}
func user32Def(h uintptr,m uint32,w,l uintptr)uintptr{r,_,_:=user32.NewProc("DefWindowProcW").Call(h,uintptr(m),w,l);return r}
