//go:build windows
package main

// appRecover se centraliza en crashlog_windows.go; no declarar otra variante en este archivo.

import("fmt";"path/filepath";"strings";"sync";"syscall";"time";"unsafe";"unicode/utf16")
const(appIDOpen=2001;appIDStatus=2006;appIDView=2007;appIDColumns=2008;appIDConfig=2009;WM_CREATE=1;WM_SIZE=5;WM_CLOSE=0x10;WM_DESTROY=2;WM_COMMAND=0x111;WM_NOTIFY=0x4E;WM_APP_IMPORT_DONE=0x8001;WM_APP_RENDER_BATCH=0x8002;WS_OVERLAPPEDWINDOW=0x00CF0000;WS_VISIBLE=0x10000000;WS_CHILD=0x40000000;WS_TABSTOP=0x00010000;WS_BORDER=0x00800000;BS_PUSHBUTTON=0;ofnExplorer=0x00080000;ofnPathMustExist=0x00000800;ofnFileMustExist=0x00001000;ofnHideReadOnly=4;ofnAllowMultiSelect=0x200;ofnNoChangeDir=8;WM_SETFONT=0x30;WM_ERASEBKGND=0x14;WM_CTLCOLORSTATIC=0x138;COLOR_WINDOW=5)
type appRect struct{Left,Top,Right,Bottom int32};type appWndClass struct{CbSize uint32;Style uint32;LpfnWndProc uintptr;CbClsExtra,CbWndExtra int32;HInstance,HIcon,HCursor,HbrBackground uintptr;LpszMenuName,LpszClassName *uint16;HIconSm uintptr};type appOpenFile struct{LStructSize uint32;_ uint32;HwndOwner uintptr;HInstance uintptr;Filter uintptr;CustomFilter uintptr;MaxCustom uint32;FilterIndex uint32;File uintptr;MaxFile uint32;_ uint32;FileTitle uintptr;MaxFileTitle uint32;_ uint32;InitialDir uintptr;Title uintptr;Flags uint32;FileOffset uint16;FileExtension uint16;DefExt uintptr;CustData uintptr;Hook uintptr;Template uintptr;Reserved uintptr;Reserved2 uint32;FlagsEx uint32}
var(appHwnd,appHInstance,appStatus,appView uintptr;appOpenButton,appColumnsButton,appConfigButton uintptr;appImportedDataset *MemoryDataset;appImportedPaths []string;appImportMu sync.Mutex;appPendingDataset *MemoryDataset;appPendingPaths []string;appPendingErr error;appSettings=loadDatasetSettings())
func appU16(s string)*uint16{p,_:=syscall.UTF16PtrFromString(s);return p};func appSetText(h uintptr,s string){if h==0{return};p:=appU16(s);user32.NewProc("SetWindowTextW").Call(h,uintptr(unsafe.Pointer(p)))};func appSetEnabled(h uintptr,b bool){if h==0{return};v:=uintptr(0);if b{v=1};user32.NewProc("EnableWindow").Call(h,v)};func appMake(p uintptr,c,t string,st uint32,x,y,w,h int,id uintptr)uintptr{a,b:=appU16(c),appU16(t);v,_,_:=user32.NewProc("CreateWindowExW").Call(0,uintptr(unsafe.Pointer(a)),uintptr(unsafe.Pointer(b)),uintptr(st),uintptr(x),uintptr(y),uintptr(w),uintptr(h),p,id,appHInstance,0);return v}
func crearVentana()uintptr{appHInstance,_,_=kernel32.NewProc("GetModuleHandleW").Call(0);c:=appU16("GestionSOExcelImporter");wc:=appWndClass{CbSize:uint32(unsafe.Sizeof(appWndClass{})),LpfnWndProc:syscall.NewCallback(appWndProcLogged),HInstance:appHInstance,HCursor:loadArrowCursor(),HbrBackground:COLOR_WINDOW+1,LpszClassName:c};user32.NewProc("RegisterClassExW").Call(uintptr(unsafe.Pointer(&wc)));t:=appU16("GestionSO V57 - Gestion de Ordenes de Venta");h,_,_:=user32.NewProc("CreateWindowExW").Call(0,uintptr(unsafe.Pointer(c)),uintptr(unsafe.Pointer(t)),WS_OVERLAPPEDWINDOW|WS_VISIBLE,0x80000000,0x80000000,1250,760,0,0,appHInstance,0);return h}
func loadArrowCursor()uintptr{v,_,_:=user32.NewProc("LoadCursorW").Call(0,32512);return v}
func appWndProc(h uintptr,m uint32,w,l uintptr)uintptr{switch m{case WM_CREATE:appHwnd=h;appBuildControls(h);return 0;case WM_SIZE:appLayout(h);return 0;case WM_ERASEBKGND:return 1;case WM_CTLCOLORSTATIC:b,_,_:=user32.NewProc("GetSysColorBrush").Call(COLOR_WINDOW);return b;case WM_COMMAND:cmd:=int(w&0xffff);if cmd==appIDOpen{appOpenXLSX(h);return 0};if cmd==appIDColumns{columnViewShowMenu(h);return 0};if cmd==appIDConfig{datasetShowConfig(h);return 0};if cmd>=filterBaseID{columnViewHandleFilterChange(uintptr(cmd));return 0};return 0;case WM_NOTIFY:if columnViewHandleNotify(l){return 0};case WM_APP_IMPORT_DONE:appFinishImport(h);return 0;case WM_APP_RENDER_BATCH:columnViewRenderBatch(uint64(w));return 0;case WM_CLOSE:user32.NewProc("DestroyWindow").Call(h);return 0;case WM_DESTROY:columnViewDestroy();user32.NewProc("PostQuitMessage").Call(0);return 0};r,_,_:=user32.NewProc("DefWindowProcW").Call(h,uintptr(m),w,l);return r}
func appBuildControls(h uintptr){appOpenButton=appMake(h,"BUTTON","ABRIR EXCEL",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_PUSHBUTTON,10,8,105,26,appIDOpen);appColumnsButton=appMake(h,"BUTTON","COLUMNAS",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_PUSHBUTTON,120,8,90,26,appIDColumns);appConfigButton=appMake(h,"BUTTON","CONFIGURACIÓN",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_PUSHBUTTON,215,8,120,26,appIDConfig);appStatus=appMake(h,"STATIC","Seleccione uno o varios archivos XLSX.",WS_CHILD|WS_VISIBLE,345,11,840,20,appIDStatus);appView=columnViewCreate(h)}
func appLayout(h uintptr){var r appRect;user32.NewProc("GetClientRect").Call(h,uintptr(unsafe.Pointer(&r)));w,hh:=int(r.Right-r.Left),int(r.Bottom-r.Top);if w<600{w=600};if hh<300{hh=300};user32.NewProc("MoveWindow").Call(appStatus,345,10,uintptr(maxInt(250,w-365)),20,1);columnViewLayout(h,w,hh)}
func parseMultiBuffer(b []uint16)[]string{end:=0;for end+1<len(b){if b[end]==0&&b[end+1]==0{break};end++};if end==0{return nil};parts:=strings.Split(string(utf16.Decode(b[:end])),"\x00");if len(parts)==1{return []string{parts[0]}};out:=[]string{};dir:=parts[0];for _,p:=range parts[1:]{if p!=""{if !filepath.IsAbs(p){p=filepath.Join(dir,p)};out=append(out,p)}};return out}
func appPickXLSX(owner uintptr)[]string{a,_:=syscall.UTF16FromString("Archivos Excel (*.xlsx)");b,_:=syscall.UTF16FromString("*.xlsx");c,_:=syscall.UTF16FromString("Todos los archivos (*.*)");d,_:=syscall.UTF16FromString("*.*");f:=append(append(append(append([]uint16{},a...),b...),c...),d...);f=append(f,0,0);buf:=make([]uint16,32768);o:=appOpenFile{LStructSize:uint32(unsafe.Sizeof(appOpenFile{})),HwndOwner:owner,Filter:uintptr(unsafe.Pointer(&f[0])),FilterIndex:1,File:uintptr(unsafe.Pointer(&buf[0])),MaxFile:uint32(len(buf)),Title:uintptr(unsafe.Pointer(appU16("Seleccionar uno o varios archivos Excel"))),Flags:ofnExplorer|ofnFileMustExist|ofnPathMustExist|ofnHideReadOnly|ofnAllowMultiSelect|ofnNoChangeDir,DefExt:uintptr(unsafe.Pointer(appU16("xlsx")))};ret,_,_:=comdlg32.NewProc("GetOpenFileNameW").Call(uintptr(unsafe.Pointer(&o)));if ret==0{return nil};return parseMultiBuffer(buf)}
func appOpenXLSX(owner uintptr){paths:=appPickXLSX(owner);if len(paths)==0{return};appSetEnabled(appOpenButton,false);appSetText(appStatus,fmt.Sprintf("Leyendo %d Excel en segundo plano...",len(paths)));go func(){start:=time.Now();docs:=make([]*xlsxDoc,0,len(paths));var e error;for _,p:=range paths{var d *xlsxDoc;d,e=ReadXLSX(p);if e!=nil{break};decorateXLSXDates(d,p);docs=append(docs,d)};var ds *MemoryDataset;if e==nil{ds,e=BuildMemoryDataset(docs,appSettings);if e==nil{applyDatasetFormula(ds,appSettings);applySavedColumnVisibility(ds)}};appImportMu.Lock();appPendingDataset=ds;appPendingPaths=append([]string{},paths...);appPendingErr=e;appImportMu.Unlock();appLog("EVENTO: consolidacion finalizada; archivos=%d duración=%s",len(paths),time.Since(start));user32.NewProc("PostMessageW").Call(owner,WM_APP_IMPORT_DONE,0,0)}()}
func applySavedColumnVisibility(ds *MemoryDataset){if ds==nil||len(appSettings.VisibleColumns)==0{return};allowed:=map[string]bool{};for _,k:=range appSettings.VisibleColumns{allowed[k]=true};for i:=range ds.Columns{ds.Columns[i].Visible=allowed[datasetColumnKey(ds.Columns[i])]}}
func saveVisibleColumns(){if columnViewVisibleColumns()==nil{return};keys:=make([]string,0);for _,c:=range columnViewVisibleColumns(){keys=append(keys,datasetColumnKey(c))};appSettings.VisibleColumns=keys;_ = saveDatasetSettings(appSettings)}
func findChildByID(p uintptr,cls string,id uintptr)uintptr{c:=appU16(cls);prev:=uintptr(0);for i:=0;i<1000;i++{h,_,_:=user32.NewProc("FindWindowExW").Call(p,prev,uintptr(unsafe.Pointer(c)),0);if h==0{return 0};if h==prev{return 0};x,_,_:=user32.NewProc("GetDlgCtrlID").Call(h);if x==id{return h};prev=h};appLog("DIAGNOSTICO: findChildByID abortado por limite; parent=0x%X clase=%s id=%d",p,cls,id);return 0}
func appFinishImport(h uintptr){defer appRecover("appFinishImport");appLog("DIAGNOSTICO: appFinishImport IN");appImportMu.Lock();ds,paths,e:=appPendingDataset,appPendingPaths,appPendingErr;appPendingDataset=nil;appPendingPaths=nil;appPendingErr=nil;appImportMu.Unlock();openButton:=appOpenButton;if openButton==0{openButton=findChildByID(h,"BUTTON",appIDOpen)};appSetEnabled(openButton,true);if e!=nil{appSetText(appStatus,"ERROR al consolidar XLSX: "+e.Error());appLog("DIAGNOSTICO: appFinishImport error=%v",e);return};if ds==nil{appSetText(appStatus,"ERROR: la importación finalizó sin datos.");appLog("DIAGNOSTICO: appFinishImport abortado: dataset nil sin error");return};appImportedDataset=ds;appImportedPaths=paths;columnViewSetDatasetSafe(ds);appSetText(appStatus,fmt.Sprintf("EN MEMORIA: %d líneas | %d duplicadas SO+ITEM | %d enriquecidas por CSV | %d archivo(s)",len(ds.Records),ds.DuplicateSO,ds.Enriched,len(paths)));appLog("EVENTO: dataset en memoria; lineas=%d duplicadas_so_item=%d CSV=%d",len(ds.Records),ds.DuplicateSO,ds.Enriched)}
func appApplySettings(){if appImportedDataset!=nil{applyDatasetFormula(appImportedDataset,appSettings);columnViewSetDatasetSafe(appImportedDataset)}}
func workbookSize(doc *xlsxDoc)(rows,cells int){if doc==nil{return};for _,rs:=range doc.Sheets{rows+=len(rs);for _,r:=range rs{cells+=len(r)}};return}
func cleanCell(s string)string{return strings.NewReplacer("\r"," ","\n"," ","\t"," ").Replace(s)}
