//go:build windows
package main

import("strings";"sync";"syscall";"unsafe")
var safeRenderMu sync.Mutex
type safeFilter struct{column DatasetColumn;text string}
func columnViewSetDatasetSafe(ds *MemoryDataset){defer appRecover("columnViewSetDatasetSafe");if ds==nil{return};columnViewDestroyFilters();viewDataset=ds;columnViewBuildFilters();columnViewRefreshSafe();appApplyVisualPolish(appHwnd)}
// columnViewRefreshSafe reconstruye solamente la estructura del ListView virtual.
// No fuerza UpdateWindow/RedrawWindow ni AutoFit: esas operaciones provocaban
// repintados sincrónicos dentro de WM_COMMAND/WM_LBUTTONUP y congelaban la UI.
func columnViewRefreshSafe(){defer appRecover("columnViewRefreshSafe");if viewList==0{return};columnViewDeleteColumns();send:=user32.NewProc("SendMessageW");if viewDataset==nil{return};visible:=columnViewVisibleColumns();for i,c:=range visible{p:=appU16(datasetColumnDisplayTitle(c));fmtCol:=lvcfmtLeft;if c.Type==ValueNumber{fmtCol=lvcfmtRight};width:=c.Width;if width<120{width=120};if width>420{width=420};lc:=lvColumn{Mask:lvcfText,Fmt:int32(fmtCol),Cx:int32(width),Text:p,SubItem:int32(i)};send.Call(viewList,lvmInsertColumnW,uintptr(i),uintptr(unsafe.Pointer(&lc)))};records:=safeFilterRecords(viewDataset,safeSnapshotFilters());itemCount:=len(records);if appSettings.SubtotalEnabled&&appSettings.SubtotalColumn!=""{itemCount++};setCount,_,_:=send.Call(viewList,lvmSetItemCountEx,uintptr(itemCount),0);appLog("DIAGNOSTICO: ListView virtual; registros=%d itemCount=%d LVM_SETITEMCOUNTEX=%d",len(records),itemCount,int(setCount));columnViewLayoutFilters(currentClientWidth());columnViewApplyFont();user32.NewProc("InvalidateRect").Call(viewList,0,1);user32.NewProc("InvalidateRect").Call(appHwnd,0,1);appLog("DIAGNOSTICO: refresco virtual diferido; item count=%d",itemCount)}
func safeSubtotalCellText(visible []DatasetColumn,records []DatasetRecord,ci int)string{if ci<0||ci>=len(visible){return ""};c:=visible[ci];targets:=map[string]bool{};if len(appSettings.SubtotalColumns)>0{for _,t:=range appSettings.SubtotalColumns{targets[strings.ToLower(strings.TrimSpace(t))]=true}}else if appSettings.SubtotalColumn!=""{targets[strings.ToLower(strings.TrimSpace(appSettings.SubtotalColumn))]=true};if ci==0&&!targets[strings.ToLower(strings.TrimSpace(c.Title))]&&!targets[strings.ToLower(strings.TrimSpace(datasetColumnDisplayTitle(c)))]{return "SUBTOTAL"};if !targets[strings.ToLower(strings.TrimSpace(c.Title))]&&!targets[strings.ToLower(strings.TrimSpace(datasetColumnDisplayTitle(c)))]{return ""};sum:=0.0;for _,r:=range records{if v,ok:=r.Values[c.ID];ok&&v.Type==ValueNumber{sum+=v.Number}};if datasetColumnIsPercent(c){sum*=100;return formatDatasetNumber(sum,datasetColumnDecimals(c))+"%"};return formatDatasetNumber(sum,datasetColumnDecimals(c))}
func safeSnapshotFilters()[]safeFilter{if viewDataset==nil{return nil};filters:=make([]safeFilter,0,len(viewFilters));for id,h:=range viewFilters{text:=strings.ToLower(strings.TrimSpace(appGetEdit(h)));if text==""{continue};for _,c:=range viewDataset.Columns{if c.ID==id{filters=append(filters,safeFilter{column:c,text:text});break}}};return filters}
func safeFilterRecords(ds *MemoryDataset,filters []safeFilter)[]DatasetRecord{if ds==nil{return nil};if len(filters)==0{return append([]DatasetRecord(nil),ds.Records...)};out:=make([]DatasetRecord,0,len(ds.Records));for _,r:=range ds.Records{ok:=true;for _,f:=range filters{if !strings.Contains(strings.ToLower(datasetCellText(r,f.column)),f.text){ok=false;break}};if ok{out=append(out,r)}};return out}
func appApplyVisualPolish(parent uintptr){defer appRecover("appApplyVisualPolish");if parent==0{return};theme:=syscall.NewLazyDLL("uxtheme.dll");setTheme:=theme.NewProc("SetWindowTheme");gdi:=syscall.NewLazyDLL("gdi32.dll");createFont:=gdi.NewProc("CreateFontW");face:=appU16("Segoe UI");size:=appSettings.FontSize;if size<8||size>32{size=10};font,_,_:=createFont.Call(uintptr(int32(-size)),0,0,0,600,0,0,0,1,0,0,0,0,uintptr(unsafe.Pointer(face)));explorer:=appU16("Explorer");buttons:=[]struct{id,x,w uintptr}{{appIDOpen,12,125},{appIDColumns,145,105},{appIDConfig,258,135}};for _,b:=range buttons{h:=uintptr(0);switch b.id{case appIDOpen:h=appOpenButton;case appIDColumns:h=appColumnsButton;case appIDConfig:h=appConfigButton};if h==0{h=findChildByID(parent,"BUTTON",b.id)};if h==0{continue};setTheme.Call(h,uintptr(unsafe.Pointer(explorer)),0);if font!=0{user32.NewProc("SendMessageW").Call(h,WM_SETFONT,font,1)};user32.NewProc("MoveWindow").Call(h,b.x,7,b.w,30,1)};status:=appStatus;if status==0{status=findChildByID(parent,"STATIC",appIDStatus)};if status!=0{if font!=0{user32.NewProc("SendMessageW").Call(status,WM_SETFONT,font,1)};user32.NewProc("MoveWindow").Call(status,410,11,uintptr(maxInt(240,currentClientWidth()-430)),22,1)}}