package main
import("archive/zip";"encoding/xml";"io";"os";"strconv";"strings";"time")
type xlsxStyleInfo struct{NumFmtID int;FormatCode string};type xlsxStylesXML struct{NumFmts struct{NumFmt []struct{ID int `xml:"numFmtId,attr"`;Code string `xml:"formatCode,attr"`} `xml:"numFmt"`} `xml:"numFmts"`;CellXfs struct{XF []struct{NumFmtID int `xml:"numFmtId,attr"`} `xml:"xf"`} `xml:"cellXfs"`};type xlsxSheetStyledXML struct{Rows []struct{R int `xml:"r,attr"`;Cells []struct{Ref string `xml:"r,attr"`;Style int `xml:"s,attr"`;Value string `xml:"v"`} `xml:"c"`} `xml:"row"`};type xlsxWorkbookXML struct{WorkbookPr struct{Date1904 bool `xml:"date1904,attr"`} `xml:"workbookPr"`}
func readZipBytes(path,name string)([]byte,error){z,e:=zip.OpenReader(path);if e!=nil{return nil,e};defer z.Close();for _,f:=range z.File{if f.Name==name{r,e:=f.Open();if e!=nil{return nil,e};defer r.Close();return io.ReadAll(r)}};return nil,os.ErrNotExist}
func readXLSXStyles(path string)([]xlsxStyleInfo,bool,error){b,e:=readZipBytes(path,"xl/styles.xml");if e!=nil{return nil,false,e};var x xlsxStylesXML;if e=xml.Unmarshal(b,&x);e!=nil{return nil,false,e};custom:=map[int]string{};for _,n:=range x.NumFmts.NumFmt{custom[n.ID]=n.Code};styles:=make([]xlsxStyleInfo,len(x.CellXfs.XF));for i,xf:=range x.CellXfs.XF{styles[i]=xlsxStyleInfo{NumFmtID:xf.NumFmtID,FormatCode:custom[xf.NumFmtID]}};date1904:=false;if wb,e:=readZipBytes(path,"xl/workbook.xml");e==nil{var w xlsxWorkbookXML;if xml.Unmarshal(wb,&w)==nil{date1904=w.WorkbookPr.Date1904}};return styles,date1904,nil}
func isExcelDateFormat(id int,code string)bool{if id>=14&&id<=22{return true};s:=strings.ToLower(code);if s==""{return false};for _,q:=range []string{"\"","'","[red]","[blue]","[green]","[black]"}{s=strings.ReplaceAll(s,q,"")};return strings.Contains(s,"yy")||strings.Contains(s,"dd")||strings.Contains(s,"mm")||strings.Contains(s,"hh")||strings.Contains(s,"ss")}
func excelSerialDate(serial float64,date1904 bool)time.Time{base:=time.Date(1899,12,30,0,0,0,0,time.Local);if date1904{base=time.Date(1904,1,1,0,0,0,0,time.Local)};days:=int64(serial);frac:=serial-float64(days);return base.AddDate(0,0,int(days)).Add(time.Duration(frac*float64(24*time.Hour)))}
func formatExcelDate(serial float64,date1904 bool)string{t:=excelSerialDate(serial,date1904);if serial==float64(int64(serial)){return t.Format("02/01/2006")};return t.Format("02/01/2006 15:04:05")}
func decorateXLSXDates(doc *xlsxDoc,path string){if doc==nil||doc.Memory==nil{return};styles,date1904,e:=readXLSXStyles(path);if e!=nil{return};for sheetName:=range doc.Sheets{b,e:=readZipBytes(path,sheetName);if e!=nil{continue};var sx xlsxSheetStyledXML;if xml.Unmarshal(b,&sx)!=nil{continue};var ms *MemorySheet;for i:=range doc.Memory.Sheets{if doc.Memory.Sheets[i].Name==sheetName{ms=&doc.Memory.Sheets[i];break}};if ms==nil{continue};for _,row:=range sx.Rows{sourceRow:=row.R;for _,cell:=range row.Cells{if cell.Style<0||cell.Style>=len(styles){continue};st:=styles[cell.Style];if !isExcelDateFormat(st.NumFmtID,st.FormatCode){continue};serial,e:=strconv.ParseFloat(strings.TrimSpace(cell.Value),64);if e!=nil{continue};col:=colFromRef(cell.Ref)-1;if col<0||col>=len(ms.Columns)||sourceRow<1{continue};var mr *MemoryRow;for i:=range ms.Rows{if ms.Rows[i].SourceRow==sourceRow{mr=&ms.Rows[i];break}};if mr==nil{continue};id:=ms.Columns[col].ID;v:=mr.Values[id];v.ColumnID=id;v.Type=ValueDate;v.Number=serial;v.Raw=formatExcelDate(serial,date1904);mr.Values[id]=v;ms.Columns[col].Type=ValueDate}}}}
