// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCalculatedColumn(arg1:string,arg2:string,arg3:boolean):Promise<main.DatasetDTO>;

export function DeleteCalculatedColumn(arg1:string):Promise<main.DatasetDTO>;

export function GetSettings():Promise<main.DatasetSettings>;

export function ImportXLSX():Promise<main.DatasetDTO>;

export function ListCalculatedColumns():Promise<Array<main.CalculatedColumn>>;

export function SaveSettings(arg1:main.DatasetSettings):Promise<void>;

export function SetColumnAlign(arg1:string,arg2:string):Promise<main.DatasetDTO>;

export function SetColumnBackground(arg1:string,arg2:string):Promise<main.DatasetDTO>;

export function SetColumnFormat(arg1:string,arg2:number,arg3:boolean,arg4:string,arg5:boolean):Promise<main.DatasetDTO>;

export function SetColumnOrder(arg1:Array<string>):Promise<void>;

export function SetColumnSignHighlight(arg1:string,arg2:boolean):Promise<main.DatasetDTO>;

export function SetColumnTitle(arg1:string,arg2:string):Promise<main.DatasetDTO>;

export function SetColumnWidth(arg1:string,arg2:number):Promise<void>;

export function SetFontSize(arg1:number):Promise<void>;

export function SetRowHeight(arg1:number):Promise<void>;

export function SetSubtotals(arg1:string,arg2:Record<string, string>):Promise<main.DatasetDTO>;

export function SetVisibleColumns(arg1:Array<string>):Promise<void>;

export function UpdateCalculatedColumn(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.DatasetDTO>;
