// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCalculatedColumn(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCalculatedColumn'](arg1, arg2, arg3);
}

export function DeleteCalculatedColumn(arg1) {
  return window['go']['main']['App']['DeleteCalculatedColumn'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportXLSX() {
  return window['go']['main']['App']['ImportXLSX']();
}

export function ListCalculatedColumns() {
  return window['go']['main']['App']['ListCalculatedColumns']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetColumnAlign(arg1, arg2) {
  return window['go']['main']['App']['SetColumnAlign'](arg1, arg2);
}

export function SetColumnBackground(arg1, arg2) {
  return window['go']['main']['App']['SetColumnBackground'](arg1, arg2);
}

export function SetColumnFormat(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetColumnFormat'](arg1, arg2, arg3, arg4, arg5);
}

export function SetColumnOrder(arg1) {
  return window['go']['main']['App']['SetColumnOrder'](arg1);
}

export function SetColumnSignHighlight(arg1, arg2) {
  return window['go']['main']['App']['SetColumnSignHighlight'](arg1, arg2);
}

export function SetColumnTitle(arg1, arg2) {
  return window['go']['main']['App']['SetColumnTitle'](arg1, arg2);
}

export function SetColumnWidth(arg1, arg2) {
  return window['go']['main']['App']['SetColumnWidth'](arg1, arg2);
}

export function SetFontSize(arg1) {
  return window['go']['main']['App']['SetFontSize'](arg1);
}

export function SetRowHeight(arg1) {
  return window['go']['main']['App']['SetRowHeight'](arg1);
}

export function SetSubtotals(arg1, arg2) {
  return window['go']['main']['App']['SetSubtotals'](arg1, arg2);
}

export function SetVisibleColumns(arg1) {
  return window['go']['main']['App']['SetVisibleColumns'](arg1);
}

export function UpdateCalculatedColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCalculatedColumn'](arg1, arg2, arg3, arg4);
}

export function LogFilePath() {
  return window['go']['main']['App']['LogFilePath']();
}
